import React, {useEffect, useState} from "react"
import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios';

import { useRouter } from 'next/router'

import Button from 'react-bootstrap/Button'
import Form from 'react-bootstrap/Form'

import styles from '../../styles/Home.module.css'

const isBrowser = () => typeof window !== "undefined"

export default function login() {

  const isBrowser = () => typeof window !== "undefined"
  const DefaultHeader = isBrowser() ? { "authorization": "Token " + localStorage.getItem('token') } : ''
  const login_credentials = DefaultHeader.authorization !== "Token null" ? DefaultHeader : ''

  let router = useRouter()
  const { redirection_url } = router.query

  const [isLoggedIn, setIsLoggedIn] = useState(false)

  useEffect(() => {
    if (isBrowser()) {
      let value = localStorage.getItem('token')
      if (value && value !== undefined && value !== 'undefined' && value !== null && value.length > 5 && value != '') {
        setIsLoggedIn(true)
      } else {
        setIsLoggedIn(false)
      }
    }
  }, [isBrowser() ? localStorage.getItem('token') : ''])

  useEffect(() => {
    if (isLoggedIn) {
      router.push(`/`)
    }
  }, [isBrowser(),redirection_url,isLoggedIn])

  function loginForm(event) {
    event.preventDefault();

    const { email, password } = event.target;

    var formData = new FormData();
    formData.append('email', email.value);
    formData.append('password', password.value);
    axios.post(process.env.NEXT_PUBLIC_API_HOST+'/api/auth/login', formData, { headers: login_credentials })
    .then(res => {
      document.getElementById("error-div").innerText ="login Successful";
      localStorage.setItem('email', res.data.user.email);
      localStorage.setItem('token', res.data.token);
      localStorage.setItem('user_id', res.data.user.id);
      router.push('/')
    }).catch(error => {
      if(error.response){
        // let error_messages = error.response.statusText + "<br>"
        let error_messages =''
        for (var key in error.response.data){
          error_messages += error.response.data[key] 
        }
        document.getElementById("error-div").innerText =error_messages;
      }
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        login
        <section className={`col-12`}>
          <Form className={`text-left`} onSubmit={(e)=> loginForm(e)}>
            <Form.Group className="mb-3" controlId="formBasicEmail">
              <Form.Label>Email address</Form.Label>
              <Form.Control type="email" name="email" placeholder="Enter email" required/>
            </Form.Group>
            <Form.Group className="mb-3" controlId="formBasicPassword">
              <Form.Label>password</Form.Label>
              <Form.Control type="password" name="password" placeholder="password" required/>
              <Form.Text className="text-muted">
                We'll never share your email with anyone else.
              </Form.Text>
            </Form.Group>
            <Button variant="primary" type="submit">
              Login
            </Button>
            <p id="error-div"></p>
          </Form>
          <style jsx>{`
              section {
                max-width: 600px;
              }
              .title {
                color: #8592e0;
              }
              .text-left {
                text-align: left;
              }
          `}</style>
        </section>
      </main>
    </div>
  )
}
