import React, {useEffect, useState} from "react"
import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios';

import { useRouter } from 'next/router'

import Button from 'react-bootstrap/Button'
import Form from 'react-bootstrap/Form'

import styles from '../../styles/Home.module.css'

const isBrowser = () => typeof window !== "undefined"

export default function Signup() {
  let router = useRouter()
  const { redirection_url } = router.query

  const [isLoggedIn, setIsLoggedIn] = useState(false)

  useEffect(() => {
    if (isBrowser()) {
      let value = localStorage.getItem('token')
      console.log(value,"varun")
      if (value && value !== undefined && value !== 'undefined' && value !== null && value.length > 5 && value != '') {
        setIsLoggedIn(true)
      } else {
        setIsLoggedIn(false)
      }
    }
  }, [isBrowser() ? localStorage.getItem('token') : ''])

  useEffect(() => {
    if (isLoggedIn) {
      router.push(`/`)
    }
  }, [isBrowser(),redirection_url,isLoggedIn])

  function submitForm(event) {
    event.preventDefault();

    const { name, email, password, account_type } = event.target;
    let user = {account_type: account_type.value,email: email.value, password: password.value, first_name: name.value}

    axios.post(`${process.env.NEXT_PUBLIC_API_HOST}/api/auth/register`,user).then(res => {
      document.getElementById("error-div").innerText ="Signup Successful";
      localStorage.setItem('email', res.data.user.email);
      localStorage.setItem('token', res.data.token);
      localStorage.setItem('user_id', res.data.user.id);
      router.push('/')
    }).catch(error => {
      if(error.response){
        // let error_messages = error.response.statusText + "<br>"
        let error_messages =''
        for (var key in error.response.data){
          error_messages += error.response.data[key] 
        }
        document.getElementById("error-div").innerText =error_messages;
      }
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Signup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        Signup
        <section className={`col-12`}>
          <Form className={`text-left`} onSubmit={(e)=> submitForm(e)}>
            <Form.Group className="mb-3" controlId="formBasicName">
              <Form.Label>Name</Form.Label>
              <Form.Control type="text" name="first_name" placeholder="Name" required/>
            </Form.Group>
            <Form.Group className="mb-3" controlId="formBasicEmail">
              <Form.Label>Email address</Form.Label>
              <Form.Control type="email" name="email" placeholder="Enter email" required/>
            </Form.Group>
            <Form.Group className="mb-3">
              <Form.Label>Account Type</Form.Label>
              <Form.Select name="account_type">
                <option value="0">Admin</option>
                <option value="1">Manager</option>
                <option value="2">Staff</option>
              </Form.Select>
            </Form.Group>
            <Form.Group className="mb-3" controlId="formBasicPassword">
              <Form.Label>password</Form.Label>
              <Form.Control type="password" name="password" placeholder="password" required/>
              <Form.Text className="text-muted">
                We'll never share your email with anyone else.
              </Form.Text>
            </Form.Group>
            <Button variant="primary" type="submit">
              Submit
            </Button>
            <p id="error-div"></p>
          </Form>
          <style jsx>{`
              section {
                max-width: 600px;
              }
              .title {
                color: #8592e0;
              }
              .text-left {
                text-align: left;
              }
          `}</style>
        </section>
      </main>
    </div>
  )
}
